[project]
name = "clinicedc-utils"
version = "0.4.0"
description = "Add your description here"
readme = "README.rst"
authors = [
    { name = "Erik van Widenfelt", email = "ew2789@gmail.com" },
]
maintainers = [
    { name = "Erik van Widenfelt", email = "ew2789@gmail.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11"
dependencies = [
    "clinicedc-constants>=1.0.1",
    "pandas>=2.3.3",
    "remote-read-sql>=1.2.3",
    "sqlalchemy>=2.0.44",
    "tqdm>=4.67.1",
]

[project.urls]
Homepage = "https://github.com/clinicedc/clinicedc-utils"
Documentation = "https://github.com/clinicedc/clinicedc-utils/docs"
Repository = "https://github.com/clinicedc/eclinicedc-utils.git"
Changelog = "https://github.com/clinicedc/clinicedc-utils/blob/main/CHANGES"


[build-system]
requires = ["uv_build>=0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = ["clinicedc_utils"]
source-exclude = ["clinicedc_utils/tests/**"]
namespace = false

[tool.ruff]
line-length = 95
indent-width = 4
target-version = "py312"
extend-exclude = [".tox", ".venv"]

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "C90",
    "COM",
    "DJ",
    "DTZ",
    "E",
    "F",
    "FA",
    "FURB",
    "I",
    "INT",
    "N",
    "PD",
    "PERF",
    "PL",
    "PLR",
    "PTH",
    "RET",
    "RUF",
    "S",
    "SIM",
    "T20",
    "TRY",
    "UP",
    "W",
    # "FIX",
]
ignore = [
    "DJ008",
    "DJ007",
    "DJ006",
    "COM812",
    "PLC0206",
    "TRY003", # temporarily
    "PLR0913", # temporarily
    "ARG001", # temporarily
    "DJ012", # temporarily
]

[tool.ruff.lint.per-file-ignores]
    "__init__.py" = ["F401"]

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.rstcheck]
ignore_directives = ["toctree"]
